[package]
name = "bacon"
version = "0.1.0"
authors = ["aftix <aftix@aftix.xyz>"]
edition = "2018"

[features]
serialize=["serde"]

[dependencies]
lazy_static="1.2"
serde={version="1.0", optional=true}
nalgebra="0.23"
float-cmp="0.8"
num-traits="0.2"
