[package]
name = "bacon"
version = "0.1.0"
authors = ["aftix <aftix@aftix.xyz>"]
edition = "2018"

[features]
serialize=["serde"]

[dependencies]
uom="0.30.0"
lazy_static="1.2.0"
serde={version="1.0.117", optional=true}
