[package]
name = "bacon-sci"
version = "0.2.3"
authors = ["aftix <aftix@aftix.xyz>"]
edition = "2018"
license="MIT"
description="Scientific computing in Rust"
homepage="https://github.com/aftix/bacon"
repository="https://github.com/aftix/bacon"
readme="README.md"

[features]
serialize=["serde"]

[dependencies]
lazy_static="1.2"
serde={version="1.0", optional=true}
nalgebra="0.23"
float-cmp="0.8"
num-complex="0.2"
num-traits="0.2"
alga="0.9"

